### ISSUE TITLE
能否考虑windows环境的使用

### ISSUE THREAD

**Issue by csbde** [bukn/sgit#1]
很喜欢sgit的思路，也想用它来管理windows下的零散配置文件。能否考虑windows下git bash 使用环境？

**Comment by bukn** [comment]
啊，这个是一个bash脚本，不知道windows下有什么类似的功能可以运行？

On Tue, Apr 1, 2014 at 12:38 PM, csbde notifications@github.com wrote:

> 很喜欢sgit的思路，也想用它来管理windows下的零散配置文件。能否考虑windows下git bash 使用环境？
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bukn/sgit/issues/1
> .

## 

http://blog.bukn.info

**Comment by csbde** [comment]
嗯，看了，你用了链接来处理。windows下链接不好使。就是在找可行的方案

**Comment by bukn** [comment]
这是一个问题，如果没有硬链的概念，就会讨厌很多，要在每次ci的时候把最新版的文件拷到repo目录下去
但我想知道，首先windows下运行bash好使么？

2014-04-01 13:31 GMT+08:00 csbde notifications@github.com:

> 嗯，看了，你用了链接来处理。windows下链接不好使。就是在找可行的方案
> 
> On 2014年4月1日 GMT+08:00PM1:29:10, Bukn notifications@github.com wrote:
> 
> > 啊，这个是一个bash脚本，不知道windows下有什么类似的功能可以运行？
> > 
> > On Tue, Apr 1, 2014 at 12:38 PM, csbde notifications@github.com
> > wrote:
> > 
> > > 很喜欢sgit的思路，也想用它来管理windows下的零散配置文件。能否考虑windows下git bash 使用环境？
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHubhttps://github.com/bukn/sgit/issues/1
> > > .
> > 
> > ## 
> > 
> > http://blog.bukn.info
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/bukn/sgit/issues/1#issuecomment-39172112
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bukn/sgit/issues/1#issuecomment-39172224
> .

## 

http://blog.bukn.info

**Comment by csbde** [comment]
如果考虑cygwin或者其他模拟环境，甚至本身git也带了bash，运行没有问题。只是win下链接很难处理

**Comment by bukn** [comment]
哦，如果bash能运行，那大概就是这样：需要在每次ci的时候把最新版的文件拷过去，另外可能还需要一个小数据库（例如sqlite或者文本文件）来存储repo目录下的每个文件对应的外部文件的目录，并且要维护这个数据库，list子命令的逻辑要改变。能想到的大概就这些

On Tue, Apr 1, 2014 at 1:44 PM, csbde notifications@github.com wrote:

> 如果考虑cygwin或者其他模拟环境，甚至本身git也带了bash，运行没有问题。只是win下链接很难处理
> 
> On 2014年4月1日 GMT+08:00PM1:40:19, Bukn notifications@github.com wrote:
> 
> > 这是一个问题，如果没有硬链的概念，就会讨厌很多，要在每次ci的时候把最新版的文件拷到repo目录下去
> > 但我想知道，首先windows下运行bash好使么？
> > 
> > 2014-04-01 13:31 GMT+08:00 csbde notifications@github.com:
> > 
> > > 嗯，看了，你用了链接来处理。windows下链接不好使。就是在找可行的方案
> > > 
> > > On 2014年4月1日 GMT+08:00PM1:29:10, Bukn notifications@github.com
> > > wrote:
> > > 
> > > > 啊，这个是一个bash脚本，不知道windows下有什么类似的功能可以运行？
> > > > 
> > > > On Tue, Apr 1, 2014 at 12:38 PM, csbde notifications@github.com
> > > > wrote:
> > > > 
> > > > > 很喜欢sgit的思路，也想用它来管理windows下的零散配置文件。能否考虑windows下git bash 使用环境？
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on
> > > > > GitHubhttps://github.com/bukn/sgit/issues/1
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > http://blog.bukn.info
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/bukn/sgit/issues/1#issuecomment-39172112
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHubhttps://github.com/bukn/sgit/issues/1#issuecomment-39172224
> > > 
> > > .
> > 
> > ## 
> > 
> > http://blog.bukn.info
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/bukn/sgit/issues/1#issuecomment-39172559
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bukn/sgit/issues/1#issuecomment-39172715
> .

## 

http://blog.bukn.info
